In [43]:
import numpy as np
import math
import statistics
import matplotlib as plt

In [2]:
# blur matrix

def create_matrix(size):  # first we need a function that creates empty matrices of the size we want (np.empty is not readable)
    if int(size) > 0:
        s = 1
        mat = []
        while s <= size:
            mat.append([0.0] * size) #the data type of matrix elements is set on creation, so float instead of int
            s += 1
        mat = np.array(mat)
    return mat


def create_blur_matrix(size):
    blurred_matrix = create_matrix(size)             # create a zeroes matrix of the required size
    if size > 1:
        for i in range(0, blurred_matrix.shape[1]):  # go through all columns of the matrix
            if i == 0:                               # set the edge case for the upper left corner
                blurred_matrix[i,i] = 0.8
                blurred_matrix[1,i] = 0.2
            elif i == (blurred_matrix.shape[1] - 1): # set the edge case for the bottom right corner
                blurred_matrix[i, i] = 0.8
                blurred_matrix[i-1, i] = 0.2
            else:
                blurred_matrix[i,i] = 0.6
                blurred_matrix[i-1,i] = 0.2
                blurred_matrix[i+1,i] = 0.2

        return blurred_matrix
    

    
blur_m = create_blur_matrix(25)



In [3]:
# delete first row
def first_zeros(vector):
    vector[5:] = 0
    
    return vector

In [4]:
# shift

def shift(vector):
    changed_copy = np.copy(vector)
    vector_copy = np.copy(vector)
    changed_copy[-1] = vector_copy[0]
    for i in range(len(vector)-1):
        changed_copy[i] = vector_copy[i+1]
        
    return changed_copy

array([0.693, 0.693, 0.   , 0.693, 0.693, 0.693, 0.693, 0.   , 0.693,
       0.693, 0.693, 0.   , 0.693, 0.   , 0.693, 0.693, 0.   , 0.   ,
       0.   , 0.693, 0.693, 0.   , 0.   , 0.   , 0.693])

In [39]:
# creating a letter dataset
# first letter clean letter
# second letter blur matrix
# third darken
# fourth bold

# M
M1 = np.array([0.99,0.99,0,0.99,0.99, 0.99,0.99,0,0.99,0.99, 0.99,0,0.99,0,0.99, 0.99,0,0,0,0.99, 0.99,0,0,0,0.99])
M2 = np.matmul(blur_m,M1)
M3 = M1*0.7
M4 = np.array([0.99,0.99,0,0.99,0.99, 0.99,0.99,0,0.99,0.99, 0.99,0.99,0.99,0.99,0.99, 0.99,0.99,0,0.99,0.99, 0.99,0.99,0,0.99,0.99])

# O
O1 = np.array([0.99,0.99,0.99,0.99,0.99,  0.99,0,0,0,0.99, 0.99,0,0,0,0.99, 0.99,0,0,0,0.99, 0.99,0.99,0.99,0.99,0.99])
O2 = np.matmul(blur_m, O1)
O3 = O1*0.7
O4 = np.array([0.99,0.99,0.99,0.99,0.99, 0.99,0.99,0.99,0.99,0.99, 0.99,0.99,0,0.99,0.99, 0.99,0.99,0.99,0.99,0.99, 0.99,0.99,0.99,0.99,0.99,])


#L
L1 = np.array([0.99,0,0,0,0,  0.99,0,0,0,0, 0.99,0,0,0,0, 0.99,0,0,0,0, 0.99,0.99,0.99,0.99,0])
L2 = np.matmul(blur_m, L1)
L3 = L1*0.7
L4 = np.array([0.99,0.99,0,0,0,  0.99,0.99,0,0,0, 0.99,0.99,0,0,0, 0.99,0.99,0.99,0.99,0, 0.99,0.99,0.99,0.99,0])


#different stuff

#E = [0,0.99,0.99,0.99,0,0,0.99,0,0,0,0,0.99,0.99,0.99,0,0,0.99,0,0,0,0,0.99,0.99,0.99,0]
#O2 = [0.99,0.99,0.99,0.99,0.99,0.99,0,0,0,0.99,0.99,0,0,0,0.99,0.99,0,0,0,0.99,0.99,0.99,0.99,0.99,0.99]
#O_blur = [0.2,0.2,0.2,0.2,0.2,0.4,0.1,0,0.1,0.4,0.4,0.1,0,0.1,0.4,0.4,0.1,0,0.1,0.4,0.2,0.2,0.2,0.2,0.2]

In [40]:
#processing dataset

def preprocessing(list_1):

    """returns a new list with its characters corrected for noise
    
    Args:
        list_1 (list): a list of integers representing a vector
        
    Returns: 
        char_processed (list): a new list corrected for noise
        
    """
    char_processed = np.copy(list_1)
 
    for i in range(len(char_processed)):     
        char_processed[i] = char_processed[i] - 0.1

    return char_processed




# M 

new_M1 = preprocessing(M1)
new_M2 = preprocessing(M2)
new_M3 = preprocessing(M3)
new_M4 = preprocessing(M4)


# O 

new_O1 = preprocessing(O1)
new_O2 = preprocessing(O2)
new_O3 = preprocessing(O3)
new_O4 = preprocessing(O4)

# L

new_L1 = preprocessing(L1)
new_L2 = preprocessing(L2)
new_L3 = preprocessing(L3)
new_L4 = preprocessing(L4)



#new_M = preprocessing(M)
#new_O = preprocessing(O)
#new_L = preprocessing(L)
#new_E = preprocessing(E)
#new_O2 = preprocessing(O2)
#new_O_blur = preprocessing(O_blur)

In [12]:
def min_max_normalise (lst):
    normalised = []
    i = 0
    for i in range(len(lst)):
        minimum = min(lst)
        maximum = max(lst)
        value = (lst[i]-minimum) / (maximum-minimum)
        i += 1
        normalised.append(value)
    return normalised


In [36]:
# so this function basically just compares the prepocessed letters to the neural network and plots the predictive
# percentages. (how sure it is). besides the preprocessing function, and the standardising function, 
# this is all we need. the rest is just for explaining what actually happens. 


# decrease bias
L_max1 = np.maximum(L1, L2)
L_max2 = np.maximum(L3, L4)
L_max = np.maximum(L_max1, L_max2)

#L_avg = np.array([new_L1, new_L2, new_L3])
#L_avg = np.average(L_avg, axis=0)

def find_percent(vector):
    
    """returns a list of floats that represents similarity to letters
    
    Args: 
        data (list): a list representing weights for each cell in the matrix (vector) letter
        
    Returns: 
        percentage (list): a list where each value represents the similarity between data and the NN. 
    """
    
    NN = [new_M1,new_O1, L_max]
    
    #NN = [new_M,new_O,new_L,new_E,new_O2,new_O_blur]
    percentage = np.matmul(NN,vector)
    
    return percentage


In [41]:
# testing the matrix

NN = [new_M1,new_O1, L_max]

print(np.matmul(NN, new_M1))
print(np.matmul(NN, new_M2))
print(np.matmul(NN, new_M3))
print(np.matmul(NN, new_M4))


print(np.matmul(NN, new_O1))
print(np.matmul(NN, new_O2))
print(np.matmul(NN, new_O3))
print(np.matmul(NN, new_O4))

print(np.matmul(NN, new_L1))
print(np.matmul(NN, new_L2))
print(np.matmul(NN, new_L3))
print(np.matmul(NN, new_L4))


#print ouput for each picture

# M

print(np.argmax(find_percent(new_M1)))
print(np.argmax(find_percent(new_M2)))
print(np.argmax(find_percent(new_M3)))
print(np.argmax(find_percent(new_M4)))

# O

print(np.argmax(find_percent(new_O1)))
print(np.argmax(find_percent(new_O2)))
print(np.argmax(find_percent(new_O3)))
print(np.argmax(find_percent(new_O4)))


# L

print(np.argmax(find_percent(new_L1)))
print(np.argmax(find_percent(new_L2)))
print(np.argmax(find_percent(new_L3)))
print(np.argmax(find_percent(new_L4)))

[11.9815   8.9422   5.30244]
[9.62926  8.15812  5.028012]
[8.01655  5.85934  3.420648]
[11.3875  10.3084   7.65468]
[ 8.9422  12.7636   8.04672]
[ 8.15812 11.58748  7.45866]
[5.88904  8.53432  5.341644]
[10.1104  11.9716   8.63478]
[2.8735 5.7148 6.8706]
[2.67748  5.12674  5.459256]
[1.64095 3.60016 4.51836]
[4.2397  6.1009  7.65468]
0
0
0
0
1
1
1
1
2
2
2
2


In [44]:
def plot(data_):
    data_ = min_max_normalise(data_)
    #Letters = ['M', 'O', 'L', 'E(3)', 'O_Scale(4)', 'O_Blur(5)']
    Letters = ['M1', 'M2', "M3"]
    percent = []
    precentage = []

    matmul_data = np.matmul(NN,data_)
    normalized_matmul = (min_max_normalise(matmul_data))
        
    for i in normalized_matmul:
        i = i*100
        percent.append(i)
    
        
  
    data_ = min_max_normalise(data_)

    Letter_dict = {Letters[i]: percent[i] for i in range(len(Letters))}
    alpha = list(Letter_dict.keys())
    nums = list(Letter_dict.values())

    fig, ax = plt.subplots()
    ax.bar(alpha, nums)
    fig.suptitle('Predictive Accuracy of Letter matching')
    ax.set_xlabel('Letters')
    ax.set_ylabel('Percentage')
    
plot(new_M2)

AttributeError: module 'matplotlib' has no attribute 'subplots'

In [ ]:
def plot2(vector):
    
    Letters = ['M1', 'M2', "M3"]
    
    ax.set_xlabel('Letters')
    ax.set_ylabel('Percentage')
    
    matplotlib.pyplot.bar(vector, height, width=0.8, bottom=None, *, align='center', data=None, **kwargs)

In [ ]:
### all that is following is not necessarilly needed atm and is more for own comprehension 

In [ ]:
print(str(np.dot(M,M))+'\t'+str(np.dot(O,M))+'\t'+str(np.dot(L,M))+'\t'+str(np.dot(E,M))+'\t'+str(np.dot(O2,M))+'\t'+str(np.dot(O_blur,M)))
print(str(np.dot(M,O))+'\t'+str(np.dot(O,O))+'\t'+str(np.dot(L,O))+'\t'+str(np.dot(E,O))+'\t'+str(np.dot(O2,O))+'\t'+str(np.dot(O_blur,O)))
print(str(np.dot(M,L))+'\t'+str(np.dot(O,L))+'\t'+str(np.dot(L,L))+'\t'+str(np.dot(E,L))+'\t'+str(np.dot(O2,L))+'\t'+str(np.dot(O_blur,L)))
print(str(np.dot(M,E))+'\t'+str(np.dot(O,E))+'\t'+str(np.dot(L,E))+'\t'+str(np.dot(E,E))+'\t'+str(np.dot(O2,E))+'\t'+str(np.dot(O_blur,E)))
print(str(np.dot(M,O2))+'\t'+str(np.dot(O,O2))+'\t'+str(np.dot(L,O2))+'\t'+str(np.dot(E,O2))+'\t'+str(np.dot(O2,O2))+'\t'+str(np.dot(O_blur,O2)))
print(str(np.dot(M,O_blur))+'\t'+str(np.dot(O,O_blur))+'\t'+str(np.dot(L,O_blur))+'\t'+str(np.dot(E,O_blur))+'\t'+str(np.dot(O2,O_blur))+'\t'+str(np.dot(O_blur,O_blur)))

In [ ]:
print(str(np.dot(new_M,new_M))+'\t'+str(np.dot(new_O,new_M))+'\t'+str(np.dot(new_L,new_M))+'\t'+str(np.dot(new_E,new_M))+'\t'+str(np.dot(new_O2,new_M))+'\t'+str(np.dot(new_O_blur,new_M)))
print(str(np.dot(new_M,new_O))+'\t'+str(np.dot(new_O,new_O))+'\t'+str(np.dot(new_L,new_O))+'\t'+str(np.dot(new_E,new_M))+'\t'+str(np.dot(new_O2,new_M))+'\t'+str(np.dot(new_O_blur,new_M)))
print(str(np.dot(new_M,new_L))+'\t'+str(np.dot(new_O,new_L))+'\t'+str(np.dot(new_L,new_L))+'\t'+str(np.dot(new_E,new_M))+'\t'+str(np.dot(new_O2,new_M))+'\t'+str(np.dot(new_O_blur,new_M)))
print(str(np.dot(new_M,new_E))+'\t'+str(np.dot(new_O,new_E))+'\t'+str(np.dot(new_L,new_E))+'\t'+str(np.dot(new_E,new_E))+'\t'+str(np.dot(new_O2,new_M))+'\t'+str(np.dot(new_O_blur,new_M)))
print(str(np.dot(new_M,new_O2))+'\t'+str(np.dot(new_O,new_O2))+'\t'+str(np.dot(new_L,new_O2))+'\t'+str(np.dot(new_E,new_O2))+'\t'+str(np.dot(new_O2,new_O2))+'\t'+str(np.dot(new_O_blur,new_M)))
print(str(np.dot(new_M,new_O_blur))+'\t'+str(np.dot(new_O,new_O_blur))+'\t'+str(np.dot(new_L,new_O_blur))+'\t'+str(np.dot(new_E,new_O_blur))+'\t'+str(np.dot(new_O2,new_O_blur))+'\t'+str(np.dot(new_O_blur,new_O_blur)))

In [ ]:
def find_percent(data):
    
    """returns a list of floats that represents similarity to letters
    
    Args: 
        data (list): a list representing weights for each cell in the matrix (vector) letter
        
    Returns: 
        percentage (list): a list where each value represents the similarity between data and the NN. 
    """
    
    NN = [new_M,new_O,new_L,new_E,new_O2,new_O_blur]
    percentage = np.matmul(NN,data)
    
    return percentage
    

    
print(matmul(new_M))
print(matmul(new_O))
print(matmul(new_L))
print(matmul(new_E))
print(matmul(new_O2))
print(matmul(new_O_blur))



In [ ]:
print(np.argmax(np.matmul(NN,new_O)))
print(np.argmax(np.matmul(NN,new_M)))
print(np.argmax(np.matmul(NN,new_L)))
print(np.argmax(np.matmul(NN,new_E)))
print(np.argmax(np.matmul(NN,new_E)))
print(np.argmax(np.matmul(NN,new_O2)))
print(np.argmax(np.matmul(NN,new_O_blur)))